server:
  port: 8081
spring:
  profiles:
    active: dev
camel:
  springboot:
    shutdownTimeout: 1
    health.indicator.enabled: true
management.security.enabled: false

info.app.name: Spring boiler plate
info.app.description: This is a Spring boot boiler plate code.
info.app.version: 1.0.0

---

spring:
  profiles: mock
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: integrationmachinelearning@gmail.com
    password: qqksjgbnxutqouzj
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mail.smtp.starttls.enable: true

mailto: integrationmachinelearning@gmail.com
mailFrom: integrationmachinelearning@gmail.com

message:   Hello from MOCK Profile
fromRoute: direct:input
toRoute: mock:output
errorQueue: activemq:errorItemQueue
healthRoute: direct:health
selectNode: sql:select * from ITEMS where sku =:#skuId?dataSource=#dataSource
---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: integrationmachinelearning@gmail.com
    password: qqksjgbnxutqouzj
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true


  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin

mailto: integrationmachinelearning@gmail.com
mailFrom: integrationmachinelearning@gmail.com
message:   Hello from DEV Profile
fromRoute: activemq:inputItemQueue
toRoute:  jdbc:dataSource
errorQueue: activemq:errorItemQueue
healthRoute: timer:health?period=10s
selectNode: sql:select * from ITEMS where sku =:#skuId?dataSource=#dataSource
---

spring:
  profiles: stage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: integrationmachinelearning@gmail.com
    password: qqksjgbnxutqouzj
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true


  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin

mailto: integrationmachinelearning@gmail.com
mailFrom: integrationmachinelearning@gmail.com
message:   Hello from DEV Profile
fromRoute: activemq:inputItemQueue
toRoute:  jdbc:dataSource
errorQueue: activemq:errorItemQueue
healthRoute: timer:health?period=10s
selectNode: sql:select * from ITEMS where sku =:#skuId?dataSource=#dataSource


---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: password
    mail:
      host: smtp.gmail.com
      port: 587
      username: integrationmachinelearning@gmail.com
      password: qqksjgbnxutqouzj
      properties.mail.smtp.auth:  true
      properties.mail.smtp.starttls.enable: true


    activemq:
      brokerUrl: tcp://localhost:61616
      user: admin
      password: admin

  mailto: integrationmachinelearning@gmail.com
  mailFrom: integrationmachinelearning@gmail.com
  message:   Hello from DEV Profile
  fromRoute: activemq:inputItemQueue
  toRoute:  jdbc:dataSource
  errorQueue: activemq:errorItemQueue
  healthRoute: timer:health?period=10s
  selectNode: sql:select * from ITEMS where sku =:#skuId?dataSource=#dataSource

---